apiVersion: v1
kind: ConfigMap
metadata:
  name: lf-tx-simulator-cm
data:
  MQ_HOST: lf-demo-mq-ibm-mq.lf-demo.svc
  # external: mq1-cp4i-ibm-mq-qm-cp4i-mq1.apps.biggs.coc-ibm.com
  MQ_PORT: "1414"
  MQ_QMGR: QM1 
  MQ_QUEUE_NAME: RAWTX
  MQ_CHANNEL: DEV.APP.SVRCONN
  KAFKA_BOOTSTRAP_SERVERS: dev-kafka-bootstrap.lf-demo.svc:9092
  KAFKA_SECURITY_PROTOCOL: PLAINTEXT
  CATEGORY_TOPIC: lf-categories
  

  